micronaut:
  session:
    http:
      cookie-path: /
  security:
    enabled: true
    authentication: session
    redirect:
      login-success: /
      login-failure: /login/authFailed
  application:
    name: nomoremeetings_backend
netty:
  default:
    allocator:
      max-order: '3'
google:
  token:
    clientId: '${GOOGLE_CLIENT_ID:814902779569-fhqsi7036j4a3jc0v52bf0n4bfchj997.apps.googleusercontent.com}'