micronaut:
  server:
    cors:
      enabled: true
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/nomoremeetings
    driverClassName: org.postgresql.Driver
    username: sa
    password: sa
    schema-generate: CREATE_DROP
    dialect: POSTGRES