version: '3.1'

services:

  db:
    image: postgres:15.2-alpine
    ports:
      - "5432:5432"
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: sa
      POSTGRES_USER: sa
      POSTGRES_DB: nomoremeetings